version: "3"

services:
#  redis:
#    image: redis:7.0.5
#    privileged: true
#    container_name: ${NAMESPACE:-bigtouy}-redis # 容器名
#    restart: always
#    ports:
#      - ${REDIS_PORT:-6379}:6379
#    volumes:
#      - ${WORKSPACE:-/workspace}/${NAMESPACE:-bigtouy}/ava_workspace/cfg/redis/redis.conf:/etc/redis/redis.conf
#      - ${WORKSPACE:-/workspace}/${NAMESPACE:-bigtouy}/ava_workspace/data/redis/data:/data
#    command: redis-server /etc/redis/redis.conf --appendonly yes --requirepass ${REDIS_PASSWORD:-bigtou123}
#  mysql:
#    image: mysql:8.0.32
#    privileged: true
#    container_name: ${NAMESPACE:-bigtouy}-mysql # 容器名
#    restart: always
#    ports:
#      - ${MYSQL_PORT:-3306}:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-bigtou123}
#    volumes:
#      - ${WORKSPACE:-/workspace}/${NAMESPACE:-bigtouy}/ava_workspace/cfg/mysql/conf:/etc/mysql/conf.d
#      - ${WORKSPACE:-/workspace}/${NAMESPACE:-bigtouy}/ava_workspace/data/mysql/data:/var/lib/mysql
#
#  postgresql:
#    image: postgres:14.5
#    privileged: true
#    container_name: ${NAMESPACE:-bigtouy}-postgresql # 容器名
#    restart: always
#    ports:
#      - ${PGSQL_PORT:-5432}:5432
#    environment:
#      POSTGRES_PASSWORD: ${PGSQL_PASSWORD:-bigtou123}
#    volumes:
#      - ${WORKSPACE:-/workspace}/${NAMESPACE:-bigtouy}/ava_workspace/data/postgresql/data:/var/lib/postgresql/data
#      - ${WORKSPACE:-/workspace}/${NAMESPACE:-bigtouy}/ava_workspace/log/postgresql/log:/var/log/postgresql
#      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
#
#  rabbitmq:
#      image: rabbitmq:management
#      privileged: true
#      container_name: ${NAMESPACE:-bigtouy}-rabbitmq # 容器名
#      restart: always
#      hostname: ${NAMESPACE:-bigtouy}-rabbitmq
#      ports:
#        - ${RABBITMQ_AMQP_PORT:-5672}:5672
#        - ${RABBITMQ_MANAGE_PORT:-15672}:15672
#      environment:
#        RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-admin}
#        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-bigtou123}
#      volumes:
#        - ${WORKSPACE:-/workspace}/${NAMESPACE:-bigtouy}/ava_workspace/data/rabbitmq/data:/var/lib/rabbitmq
#        - ${WORKSPACE:-/workspace}/${NAMESPACE:-bigtouy}/ava_workspace/log/rabbitmq/log:/var/log/rabbitmq
#
#  consul:
#      image: consul:1.13.3
#      privileged: true
#      container_name: ${NAMESPACE:-bigtouy}-consul # 容器名
#      restart: always
#      ports:
#        - ${CONSUL_PORT:-8500}:8500
#      volumes:
#        - ${WORKSPACE:-/workspace}/${NAMESPACE:-bigtouy}/ava_workspace/cfg/consul/conf:/consul/config
#        - ${WORKSPACE:-/workspace}/${NAMESPACE:-bigtouy}/ava_workspace/data/consul/data:/consul/data
#      command: agent -server -bootstrap-expect=1 -ui -bind=0.0.0.0 -client=0.0.0.0

  nginx:
    image: nginx:1.27
    privileged: true
    container_name: ${NAMESPACE:-bigtouy}-nginx # 容器名
    restart: always
    ports:
      - ${NGINX_PORT:-80}:80
      - ${NGINX_PORT_SSL:-443}:443
    environment:
      DOMAIN_SUFFIX: ${DOMAIN_SUFFIX:-bigtou.cn}
      WEBSITE_SERVER: ${WEBSITE_SERVER:-127.0.0.1:8001}
    # volumes:
    #   - ${WORKSPACE:-/workspace}/${NAMESPACE:-bigtouy}/ava_workspace/log/nginx/log:/var/log/nginx
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf
    volumes:
      - ${WORKSPACE:-/workspace}/${NAMESPACE:-bigtouy}/ava_workspace/log/nginx/log:/var/log/nginx
      - ./nginx.conf.template:/etc/nginx/conf.d/default.conf.template
      # 证书配置
      - ./cert:/etc/nginx/cert
    command: /bin/bash -c "envsubst '$${DOMAIN_SUFFIX} $${WEBSITE_SERVER}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
